dazuma/toys

toys-core/lib/toys/loader.rb, toys-core/test/test_dsl.rb
=> Add ability to use symbols for `alias_tool` and `delegate_to`

toys-core/CHANGELOG.md, toys-core/lib/toys/cli.rb, toys-core/lib/toys/loader.rb, toys-core/lib/toys/module_lookup.rb, toys-core/lib/toys/source_info.rb, toys-core/lib/toys/utils/terminal.rb, toys-core/test/lookup-cases/lib-dirs/.lib/hello.rb, toys-core/test/lookup-cases/lib-dirs/foo.rb, toys-core/test/lookup-cases/lib-dirs/ns/.lib/hello.rb, toys-core/test/lookup-cases/lib-dirs/ns/bar.rb, toys-core/test/test_cli.rb, toys-core/test/test_loader.rb, toys/CHANGELOG.md, toys/docs/guide.md
=> Add .lib directories to the Ruby load path when executing a tool

.editorconfig, README.md, toys-core/README.md, toys/README.md, toys/docs/guide.md
More info here: http://editorconfig.org/
=> Add EditorConfig file

.toys/update-bundles.rb
=> Add `update-bundles` tool for `toys-dev`

toys-core/CHANGELOG.md, toys-core/lib/toys/standard_mixins/exec.rb, toys-core/test/mixins/test_exec.rb, toys/CHANGELOG.md
=> Fixed behavior of setting exit_on_nonzero_status explicitly to false

.toys/release/.toys.rb, .toys/release/trigger.rb, toys-core/.toys.rb, toys/.toys.rb
Signed-off-by: Daniel Azuma <dazuma@gmail.com>
=> chore: Some CI updates

.toys/release/.toys.rb, toys-core/Gemfile, toys-core/lib/toys/utils/gems.rb, toys-core/lib/toys/utils/gems/gemfile.rb, toys/Gemfile
=> fix: Support toys itself as a bundle dependency

.toys/release/.toys.rb, toys-core/lib/toys/utils/exec.rb, toys-core/test/utils/test_exec.rb
=> fix: Exec::Result reports signals correctly

toys-core/lib/toys/utils/help_text.rb, toys-core/test/utils/test_help_text.rb
=> fix: Improve generated help for delegates

toys/README.md, toys/docs/guide.md
#57 notes that the guide doesn't cover this case.
=> docs: Update toys guide to cover bundle static

toys-core/docs/guide.md, toys-core/lib/toys/dsl/tool.rb, toys-core/lib/toys/loader.rb, toys-core/test/test_dsl.rb, toys/docs/guide.md
=> feat: Support truncating the load path from a directive

toys-core/lib/toys/standard_mixins/bundler.rb, toys-core/lib/toys/utils/gems.rb, toys-core/test/gems-cases/bundle-using-gemspec/run_test.rb
=> feat: Support retries in the bundler integration

toys-core/lib/toys/dsl/tool.rb, toys-core/lib/toys/tool_definition.rb, toys-core/test/test_tool_definition.rb
=> feat: Add preferences for tools

.gitignore, toys-core/lib/toys/utils/gems.rb, toys-core/test/gems-cases/bundle-with-vendored-path/.bundle/config, toys-core/test/gems-cases/bundle-with-vendored-path/Gemfile, toys-core/test/gems-cases/bundle-with-vendored-path/run_test.rb, toys-core/test/utils/test_gems.rb
=> fix: Bundler integration honors local bundle configs

toys/lib/toys/templates/clean.rb, toys/lib/toys/templates/gem_build.rb, toys/lib/toys/templates/minitest.rb, toys/lib/toys/templates/rake.rb, toys/lib/toys/templates/rdoc.rb, toys/lib/toys/templates/rspec.rb, toys/lib/toys/templates/rubocop.rb, toys/lib/toys/templates/yardoc.rb, toys/test/test_clean.rb, toys/test/test_gem_build.rb, toys/test/test_minitest.rb, toys/test/test_rake.rb, toys/test/test_rdoc.rb, toys/test/test_rspec.rb, toys/test/test_rubocop.rb, toys/test/test_yardoc.rb
Closes #121 
Also improves the test coverage on the build-related templates.
=> feat: It is now possible to set the context directory individually in the standard build templates

toys-core/lib/toys/standard_mixins/git_cache.rb, toys-core/lib/toys/utils/git_cache.rb, toys-core/test/mixins/test_git_cache.rb, toys-core/test/utils/test_git_cache.rb
This is the first step toward loading tools from git
=> feat: Implement a git cache

toys-core/lib/toys/utils/terminal.rb, toys-core/test/utils/test_terminal.rb
=> feat: Terminal util honors NO_COLOR

toys-core/lib/toys/standard_mixins/exec.rb, toys-core/lib/toys/utils/exec.rb, toys-core/test/utils/test_exec.rb
=> fix: Ensure all exec commands have a default log string

toys-core/lib/toys/standard_middleware/show_help.rb, toys-core/lib/toys/standard_mixins/pager.rb, toys-core/lib/toys/standard_mixins/xdg.rb, toys-core/lib/toys/utils/pager.rb, toys-core/test/mixins/test_pager.rb, toys-core/test/utils/test_pager.rb
=> feat: Implement pager util and mixin

.toys/release/.lib/release_requester.rb
=> chore(release): include individual released gems info in commit message

.github/workflows/release-hook-on-closed.yml, .github/workflows/release-hook-on-push.yml, .github/workflows/release-perform.yml, .github/workflows/release-request.yml, .github/workflows/release-retry.yml, .toys/.data/releases.yml, .toys/release/.data/templates/release-hook-on-closed.yml.erb, .toys/release/.data/templates/release-hook-on-open.yml.erb, .toys/release/.data/templates/release-hook-on-push.yml.erb, .toys/release/.data/templates/release-perform.yml.erb, .toys/release/.data/templates/release-request.yml.erb, .toys/release/.data/templates/release-retry.yml.erb, .toys/release/.lib/release_requester.rb, .toys/release/.lib/release_utils.rb, .toys/release/.lib/repo_settings.rb
=> chore: support configuration of release commit tags
